sudo: false
language: go

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

os:
  - linux
  #- osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get ./...
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./dfl/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./dfljs/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./plugins/dfl/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./cmd/dfl/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./cmd/dfl.js/
  - cd dfl
  - go fmt
  - go test
  - cd ../dfljs
  - go fmt
  - cd ../cmd/dfl
  - go fmt
  - go build
  - cd ../../cmd/dfl.js
  - go fmt
  - go build